### ISSUE TITLE
Junit

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#101]
I am still trying to solve this : https://github.com/hatunet/spring-data-mybatis/issues/89

Apparently the findBySiteServiceId return null. I would like to add a unit test to demonstrate my case.

I am trying to load a repository in Junit but I can't configure the application context correctly.

Did you manage to load mybatis repositories within Junit tests ?

**Comment by easybest** [comment]
here is a sample:

https://github.com/hatunet/spring-data-mybatis/blob/master/src/test/java/org/springframework/data/mybatis/repository/UserRepositoryTests.java
