### ISSUE TITLE
Circular dependencies between sqlSessionFactory and dataSourceInitializer

### ISSUE THREAD

**Issue by freemanpolys** [easybest/spring-data-mybatis#102]
Hi,

I have this issue when adding spring-boot-starter-data-mybatis dependency in Spring Boot 1.5.1.RELEASE.

`
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

   springDataMybatisApplication (field com.example.mapper.MyUserMapper com.example.SpringDataMybatisApplication.myUserMapper)
      ↓
   myUserMapper defined in file [/Users/sar/Documents/Projets/James-SpringBoot-Sandbox/spring-data-mybatis/target/classes/com/example/mapper/MyUserMapper.class]
┌─────┐
|  sqlSessionFactory defined in class path resource [org/springframework/data/mybatis/autoconfiguration/MybatisRepositoriesAutoConfiguration.class]
↑     ↓
|  dataSource defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Tomcat.class]
↑     ↓
|  dataSourceInitializer
└─────┘
`

**Comment by easybest** [comment]
can you show me your pom.xml?
