### ISSUE TITLE
Can't update entity field to null

### ISSUE THREAD

**Issue by RushPVA** [easybest/spring-data-mybatis#111]
Code sample:
```
//insert
User user = new User();
user.setUsername("test");
user.setPassword("test");
user.setName("test");
userMapper.insert(user);

```
```
//update
user.setPassword("test2");
user.setName(null);
userMapper.update(user);
```

Password was updated, but name was not.

**Comment by yezhoujie** [comment]
hi:
it is the strategy when it handle update,it will not to update when a property is null, to make more simpler to update. you just need to set the property which you need to update, so that you don't need to get the whole  object with full properties from db.
in your case, you should to use "" or other value to  take the place of null.

**Comment by easybest** [comment]
1. set name with value ""
2. write a update statement in Mapper xml file by yourself

**Comment by RushPVA** [comment]
may be better to have choice between strategies in configuration? Because updating fields into null is the default strategy for other spring data repositories.

**Comment by RushPVA** [comment]
1) using "" for empty field is not good aproach for me(for example it ruins not null constraint in data base, also i need additional checks - name != null && !name.isEmpty()
2) i choose  spring data to not write boiler plate code, so writing custom xml mappers for simple updates is not right way

**Comment by kopax** [comment]
I must agree with @RushPVA, it's surprising this update doesn't set to null in database. Would be nice to have both choice.

**Comment by RushPVA** [comment]
and one more:
ok "" for empty string fields, but what should i set for numbers or dates?

**Comment by hatunet** [comment]
I will add a configuration item  to decide which strategy to use about this problem in 1.0.14 version.

**Comment by easybest** [comment]
in 1.0.14:

update method will not ignore null property, and added two new methods:

```java

    <S extends T> S updateIgnoreNull(S entity);

    <S extends T> S saveIgnoreNull(S entity);
```
These two methods will ignore null property when update.

**Comment by RushPVA** [comment]
Welldone!!!
P.S. I am fun of mybatis, and i am glad to see that spring data mybatis project finally appeared in the developing.
