### ISSUE TITLE
Support schema for @Entity

### ISSUE THREAD

**Issue by RushPVA** [easybest/spring-data-mybatis#113]
Now i can't find any possiibility to define schema for table.

**Comment by easybest** [comment]
so far,  we have no plans to support generate database schema automatically, because it's not suitable for mybatis.

You can specifically talk about your needs and ideas. @RushPVA

**Comment by RushPVA** [comment]
This functionallity  is not for database schema generation. this is for query generation in mybatis. For example:
@Entity(table="users", schema="customschema") will generate "select" query(and other - insert,update, etc) like  - "SELECT ... FROM customschema.users ...". As i know most of databases support schemas.

**Comment by easybest** [comment]
aha i see.

you can use @Query annotation

**Comment by RushPVA** [comment]
But default functionality of MybatisRepository will not work then...

**Comment by kopax** [comment]
Any update on this ? I am also looking for this.
Because we create unit modules, I would like to run db migration in each container and store data in separate schema. Would be awesome to get `spring-data-mybatis` compatible with multiple schema.
