### ISSUE TITLE
ID生成器貌似不管用

### ISSUE THREAD

**Issue by cn-src** [easybest/spring-data-mybatis#118]
@Id(strategy = Id.GenerationType.UUID)好像没生成id。也没看到需要指定生成器的地方。

**Comment by dargoner** [comment]
public @interface Id {

    GenerationType strategy() default AUTO;

    boolean composite() default false;

    enum GenerationType {
        AUTO,
        SEQUENCE,
        IDENTITY,
        ASSIGNATION,
        UUID, TABLE, DISTRIBUTED;
    }
}

ASSIGNATION、UUID、DISTRIBUTED 好像没有实现

**Comment by easybest** [comment]
是的，目前还没实现。下个版本会实现

**Comment by huyaro** [comment]
@hatunet If possible, add custom generator configuration options to the ID generator whenever possible. thanks!

**Comment by easybest** [comment]
accept
