### ISSUE TITLE
How to use @Param("...") in order to search using the spring-data-rest endpoint?

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#119]
I have exposed to __spring-data-rest__ a search function  `findByLogin`: 

```json
{
 "_links": {
   "findByLogin": {
     "href": "http://localhost:8080/managers/search/findByLogin{?projection}",
     "templated": true
   },
   "self": {
     "href": "http://localhost:8080/managers/search"
   }
 }
}
```

All the repository that I use with `@Param` annotation return null result set, eg:

```java
@RepositoryRestResource(collectionResourceRel = "managers", path = "/managers", excerptProjection = ManagerProjection.class)
public interface ManagerRepository extends MybatisRepository<Manager, Long> {
	public Manager findByLogin(@Param("login") String login);
}
```

I have tested the query by calling the method from a controller without `@Param("login")` and it work fine.

As soon as I name my query with `@Param`, the result set become null and my endpoint is not query-able.

This is the relevant part of `Manager.java`

```java
@Entity(table = "MANAGER")
public class Manager extends VersionId implements UserDetails, CredentialsContainer {

	@JdbcType(VARCHAR)
	@Column(name = "LOGIN")
	private String login;

	@JsonIgnore
	@JdbcType(VARCHAR)
	@Column(name = "PASSWORD")
	private String password;

	@JdbcType(VARCHAR)
	@TypeHandler(RoleListTypeHandler.class)
	@Column(name = "AUTHORITIES")
	@NotNull
	private List<Role> roleList;
```

This lead me to the following question :

What should be the value passed to `@Param` annotation ? 

1. Column name?
1. Attribute name? 
1. Something else?

**Comment by kopax** [comment]
any update on this?

**Comment by easybest** [comment]
``public Manager findByLogin(@Param("login") String login);``
no need to add @Param under these circumstances

**Comment by kopax** [comment]
Well, in that case I must have misunderstood something. How do you pass parameters to your REST search endpoints ?

**Comment by kopax** [comment]
I am creating a ReactJS component `<SearchManager />` and I can't pass anything to my method. Did you find a way to do it ? Are you assuming this should work even in REST without `@Param`?
