### ISSUE TITLE
ID field not in json response body

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#122]
When I get an entity using the `/entity` url, I have the `id` field present in the json response body.

If I call a single entity using `/entity/1` endpoint, my `id` field is not in the returned json response body.

The only way I have to identify my resources is the link href.

Is there a way to force the inclusion ?

**Comment by kopax** [comment]
This is a normal behavior explained in spring-data-rest documentation.

**Comment by easybest** [comment]
yes
