### ISSUE TITLE
可否给一个springmvc整合的例子?

### ISSUE THREAD

**Issue by caocf** [easybest/spring-data-mybatis#124]
可否给一个springmvc整合的例子?

**Comment by kopax** [comment]
https://github.com/hatunet/spring-data-mybatis-samples

**Comment by caocf** [comment]
@kopax 谢谢，但是这个工程好像不是xml配置的？

**Comment by kopax** [comment]
@caocf 你在说弹簧配置吗？
基本上是一回事
你可以找到很多有关xml和java配置的文章：

https://www.mkyong.com/spring/spring-mixing-xml-and-javaconfig/

你要配置什么bean？

**Comment by caocf** [comment]
@kopax yes ,i want to know spring-data-mybatis how to configure in xml ?

**Comment by kopax** [comment]
I am not using xml in any of my spring projects. Except xml mybatis mappers.
Could you share what configuration you currently have so I can see which part you are missing , maybe I can help.

**Comment by caocf** [comment]
like this?
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:tx="http://www.springframework.org/schema/tx" xmlns:aop="http://www.springframework.org/schema/aop"
	xsi:schemaLocation="
        http://www.springframework.org/schema/beans 
        http://www.springframework.org/schema/beans/spring-beans-4.2.xsd        
        http://www.springframework.org/schema/context 
        http://www.springframework.org/schema/context/spring-context-4.2.xsd
        http://www.springframework.org/schema/tx 
     	http://www.springframework.org/schema/tx/spring-tx-4.2.xsd
		http://www.springframework.org/schema/aop
		http://www.springframework.org/schema/aop/spring-aop-2.5.xsd">

	<tx:annotation-driven />
	<context:property-placeholder location="classpath:db.properties" />
	
	<bean id="dataSource" class="com.alibaba.druid.pool.DruidDataSource"
		init-method="init" destroy-method="close">
		<property name="url">
			<value>${jdbc.url}</value>
		</property>
		<property name="username">
			<value>${jdbc.username}</value>
		</property>
		<property name="password">
			<value>${jdbc.password}</value>
		</property>
		<property name="initialSize">
			<value>${jdbc.initialSize}</value>
		</property>
		<property name="maxActive">
			<value>${jdbc.maxActive}</value>
		</property>
		<property name="proxyFilters">
			<list>
				<ref bean="stat-filter" />
				<ref bean="wall-filter" />
			</list>
		</property>
	</bean>
	
	<bean id="stat-filter" class="com.alibaba.druid.filter.stat.StatFilter">
		<property name="slowSqlMillis" value="1000" />
		<property name="logSlowSql" value="true" />
		<property name="mergeSql" value="true" />
	</bean>

	<bean id="wall-filter" class="com.alibaba.druid.wall.WallFilter">
		<property name="dbType" value="mysql" />
		<property name="config" ref="wall-filter-config" />
	</bean>

	<bean id="wall-filter-config" class="com.alibaba.druid.wall.WallConfig">
		<property name="multiStatementAllow" value="true" />
	</bean>

	<bean id="druid-stat-interceptor" class="com.alibaba.druid.support.spring.stat.DruidStatInterceptor"></bean>
	<bean id="druid-stat-pointcut" class="org.springframework.aop.support.JdkRegexpMethodPointcut" scope="prototype">
		<property name="patterns">
			<list>
				<value>io.renren.controller.*</value>
				<value>io.renren.service.*</value>
			</list>
		</property>
	</bean>
	<aop:config>
		<aop:advisor advice-ref="druid-stat-interceptor" pointcut-ref="druid-stat-pointcut"/>
	</aop:config>

	<bean id="transactionManager"
		class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
		<property name="dataSource">
			<ref bean="dataSource" />
		</property>
	</bean>

	<bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
		<property name="configLocation" value="classpath:mybatis.xml" />
		<property name="dataSource" ref="dataSource" />
	</bean>

	<bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
		<property name="basePackage" value="io.renren.dao" />
	</bean>
</beans>

**Comment by caocf** [comment]
i want to know how to config sqlSessionFactory when i user spring-data-mybatis?

**Comment by kopax** [comment]
This is **mybatis** configuration not **spring-data-mybatis**

I don't know the exact synthax in xml, but for information, this is my `SqlSessionFactoryBean` in JavaConfig : 

```java
	@Bean
	public SqlSessionFactoryBean sqlSessionFactory() throws Exception {
		final SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
		sessionFactory.setDataSource(dataSource.dataSource());
		sessionFactory.setTypeHandlers(new TypeHandler[] {
		    new InstantTypeHandler(),
			new LocalDateTimeTypeHandler(),
			new LocalDateTypeHandler(),
			new LocalTimeTypeHandler(),
			new OffsetDateTimeTypeHandler(),
			new OffsetTimeTypeHandler(),
			new ZonedDateTimeTypeHandler(),
			new YearTypeHandler(),
		        new MonthTypeHandler(),
			new RoleListTypeHandler(),
			new CommaSeparatedTypeHandler(),
			new JsonMapTypeHandler(),
		});
		sessionFactory.setTypeAliases(new Class[] {
			Role.class,
			Manager.class,
			OAuthClient.class,
			Customer.class,
			Company.class,
			SiteService.class,
		});
		return sessionFactory;
	}
```

What you need is to configure in such a way depending the `sqlSessionFactoryBean`

You can find more details here : http://www.mybatis.org/spring/factorybean.html

Hope this help

**Comment by easybest** [comment]
https://github.com/easybest/spring-data-mybatis-samples
