### ISSUE TITLE
problem while using top

### ISSUE THREAD

**Issue by yezhoujie** [easybest/spring-data-mybatis#125]
Accroding to spring data JPA example "User findTopByOrderByAgeDesc();"
a problem shows when using "Entiry findTopByOrderByLastCrawleTimeDesc();". The sql is "select `crawledLog`.id as `id`,`crawledLog`.last_crawle_time as `lastCrawleTime`,`crawledLog`.ota_name as `otaName` from CrawledLog `crawledLog`  where   ( )  order by `crawledLog`.last_crawle_time DESC", there is nothing in WHERE.

**Comment by easybest** [comment]
Not JPA!
it comply with a standard of Spring Data

**Comment by easybest** [comment]
resolved
