### ISSUE TITLE
建议优化通过接口中的方法名生成对应的查询

### ISSUE THREAD

**Issue by luckyrockyma** [easybest/spring-data-mybatis#127]
建议优化通过接口中的方法名生成对应的查询，对生成的sqlmap中采用动态SQL的方式，增加参数是否为NULL的判断，具体来说在PartTreeMybatisQuery的buildQueryCondition方法中，增加类似
 if(part.getType()!=Type.IS_NULL&&part.getType()!=Type.IS_NOT_NULL)
                	builder.append("<if test=\""+property.getName()+" != null >");
这样的逻辑

**Comment by easybest** [comment]
你可以提交个pr吗
