### ISSUE TITLE
这两个annotation.Id接口能不能合到一起

### ISSUE THREAD

**Issue by junphine** [easybest/spring-data-mybatis#129]
org.springframework.data.annotation.Id
org.springframework.data.mybatis.annotations.Id
有时候一种entity需要使用多个orm方案。

比如让org.springframework.data.mybatis.annotations.Id 继承org.springframework.data.annotation.Id

**Comment by easybest** [comment]
```java
@Retention(RetentionPolicy.RUNTIME)
@Target(value = {FIELD, METHOD, ANNOTATION_TYPE})
@org.springframework.data.annotation.Id
public @interface Id {
}
```
已经标记为 @org.springframework.data.annotation.Id
