### ISSUE TITLE
Nullpointer exception : failed to load beans : persistentEntity.getIdProperty() is null

### ISSUE THREAD

**Issue by jguidoux** [easybest/spring-data-mybatis#132]
Hello :)
I'm trying to use my-batis-data with spring-boot.
Yesterday I successfully add mybatis with spring-boot and an embedded database (h2)

So today I try to use mybatis-spring-bata:
I add this in my gradle configuration file : 

```   
 compile 'com.ifrabbit:spring-data-mybatis:1.0.15.RELEASE'
```
Then my applications properties look like this : 

```
mybatis.typeAliasesPackage=fr.slickteam.cities.model
mybatis.mapperLocations=classpath*:**/mappers/*.xml
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
logging.level.org.springframework.data.mybatis.samples=debug

spring.datasource.schema=classpath:sql/schema.sql
spring.h2.console.path=/myconsole
```
My spring configuration file look like this : 

```
@SpringBootApplication
@PropertySource("classpath:/env.properties")
@EnableMybatisRepositories
class Application


fun main(args: Array<String>) {


    SpringApplication.run(Application::class.java, *args)
}

```
Thy syntax can look strange for you, because I use kotlin as programming language.

My repository interface look like this : 
```
@Mapper
interface IUserMapper : CrudRepository<User, Int>{
	fun findByUsername(username: String?): User?
	fun findByEmail(email: String): User?
}
```
IUserMapper : CrudRepository means extends:

And my mapper xml file look like this : 

```
<mapper namespace="fr.slickteam.cities.mappers.IUserMapper">

    <resultMap id="userResultMap" type="User">
        <id property="id" column="id" />
        <result property="login" column="login" />
        <result property="email" column="email" />
        <result property="encodedPassword" column="encodedPassword" />
    </resultMap>

    <select id="findByUsername" resultMap="userResultMap">
        select id, login, email, encodedPassword from users WHERE login=#{username}
    </select>
    <select id="findByEmail" resultMap="userResultMap">
        select id, login, email, encodedPassword from users WHERE email=#{email}
    </select>
</mapper>
```
When I launch  the application, springs failed to create bean because : 

```
Caused by: java.lang.NullPointerException
	at org.springframework.data.mybatis.repository.support.MybatisSimpleRepositoryMapperGenerator.buildByIdCaluse(MybatisSimpleRepositoryMapperGenerator.java:318)
```
In this méthode , there is this code : 
```
        final MybatisPersistentProperty idProperty = persistentEntity.getIdProperty();
        if (idProperty.isCompositeId()) {
```
But idProperty is null.
Do you have an idea why ?
And do you know how can I fix it ?

I hope I post it in the good place:

Thanks 

Jérémie

**Comment by jguidoux** [comment]
Apparently I found one solution. now my Entity had the annotation @Entity and extends LongId

```
@Entity
data class User(


		@get:NotEmpty
		@get:Size(min = 3, max = 12)
		@get:UniqueLogin
		var login: String = "",

		@get:NotEmpty
		@get:Email
		@get:Size(max = 40)
		@get:UniqueEmail
		var email: String = "",

		@get:NotEmpty
		@get:Size(min = 5, max = 40)
		var encodedPassword: String = "") : LongId()
```
But the save method don't work.
```
		val savedUser = userMapper.save(model)
		return savedUser.id
```
the id of savepUser is null.
I don't think the user is stored in the database. Do you know whiy ?

Thanks.

Jérémie

**Comment by jguidoux** [comment]
Ok. I understood the problem:
first I did a melt between mapper class and repository with spring-data and I didn't really understood how it works.
the problem was the the interface didn't really mapped my BDD table colunms name:
So i change my database name and column name to match the java code.
but, if I was in a position where I couldn't modify the database. how can i configure my user class to map the good table with the good column name.
I thought it was on the file  usermapper.xml as I did with mybatis without added spring-data. but now this file is ignored by my repository. so, how can i do ?

Thanks you :)

**Comment by easybest** [comment]
you can use ``@Column`` annotation
and ``@Entity(table="table_name")``

**Comment by jguidoux** [comment]
Ok. Thanks for the answer :)

But I have the impression to use an ORM like hibernate.
I'm a new user of mybatis and especially spring-data-mybatis (so pardon me if I ask stupid questions ^^), but I can see the interest to use mybatis to replace an orm like hibernate.
But with spring-data-mybatis. I have the impression to use it as I use spring-data-jpa. I don't feel the strength points of mybatis with this library.
If I understand well we use she same annotation as with hibernate or JPA and we don't use the mapper files of mybatis which are for me the strengths points of mybatis.

So for you, when we use mybatis, why using spring-data-mybatis ?
Or. when we use spring-data, why choosing mybatis instead of a classical hibernate.

An other question which is not directly link.
In the MybatisRepository interface, there is some methods which conditions that I don't know how to use.
can you explain me how to use this method for example ?
```    
<X extends T> T findOne(X condition, String... columns);
```
In particular it is the parameter 'condition' which is strange for me.

I hope my questions on github does not disturb you. If there is a better place for them, don't hesitate to show me the place.
As I said. I just discover mybatis and spring-data-mybatis, and I think that to use well a framework we need to understand the objectives, the advantage/disadvantage, the problematic answers of this frameworks.

Thanks for you help
