### ISSUE TITLE
Can not download 1.0.16 & 1.0.17 jar from maven

### ISSUE THREAD

**Issue by thc75** [easybest/spring-data-mybatis#134]
maven can't download jar after 1.0.15.
And the last version in 
[http://repo1.maven.org/maven2/com/ifrabbit/spring-boot-starter-data-mybatis/](http://repo1.maven.org/maven2/com/ifrabbit/spring-boot-starter-data-mybatis/)
is 1.0.15

**Comment by easybest** [comment]
Issued a problem when release to maven central repository.

**Comment by easybest** [comment]
It was fixed

**Comment by easybest** [comment]
use 1.0.17.RELEASE
