### ISSUE TITLE
SELECT_CONDITION_INNER: findAll条件查询不能生成where语句

### ISSUE THREAD

**Issue by f0rb** [easybest/spring-data-mybatis#136]
自动生成的xml里的<sql id="SELECT_CONDITION_INNER"></sql>, 内容是空的, 这个需要自己开发吗?

**Comment by yezhoujie** [comment]
在对应的domain 需要查询的字段上增加注释@Condition

**Comment by easybest** [comment]
这个是预留的，可以自己写SELECT_CONDITION_INNER

**Comment by f0rb** [comment]
@yezhoujie org.springframework.data.mybatis.annotations.Condition? 似乎没有效果
@hatunet 自己怎么写呢? 没有看到相关文档, 看源码似乎也没有引入的方法!
