### ISSUE TITLE
MybatisRepository的update方法使用@Version的问题

### ISSUE THREAD

**Issue by inmaytide** [easybest/spring-data-mybatis#143]
在实体类中的version字段添加@Version注解，执行update时会自动添加version=?的条件，
但是当主键ID是Long类型的时候生成的sql执行失败。
看日志生成的sql如下
```sql
update sys_role SET code=?,create_time=?,creator=?,description=?,name=?,update_time=?,updater=?,version=version+1 where id=?and version=?
```

是id=?and这里少个空格引起的，但是我没找到应该在哪改

**Comment by kopax** [comment]
I am hitting the same issue. Thanks for the fix.

**Comment by jensolzhu** [comment]
在MybatisSimpleRepositoryMapperGenerator的281行增加一空格，类似：
builder.append(" and ") ...
