### ISSUE TITLE
能否将方法命名确定到字段

### ISSUE THREAD

**Issue by 1013785085** [easybest/spring-data-mybatis#147]
比如：String findNameById(String id);=select name from table where id = :id; 
int updateNameByid(Entity entiy); update table set name=:name where id =:id;

**Comment by easybest** [comment]
下个版本提供

**Comment by 1013785085** [comment]
感谢接受建议，不知支持不支持存储过程和函数的调用命名，方法可变参数个数（User getByIds(int ... id)），能否为每个mapper提供一个基础resultMap，这样当写自定义SQL时候不用写基本的映射，直接继承然后扩展

**Comment by easybest** [comment]
现在就有基础的ResultMap

**Comment by easybest** [comment]
use @SelectColumns annotation. https://github.com/hatunet/spring-data-mybatis/blob/0ae92d7aa1e3415001dfc092781c1deda37539ee/spring-data-mybatis/src/test/java/org/springframework/data/mybatis/repository/sample/UserRepository.java#L162

another way:
use @Query annotation. https://github.com/hatunet/spring-data-mybatis/blob/0ae92d7aa1e3415001dfc092781c1deda37539ee/spring-data-mybatis/src/test/java/org/springframework/data/mybatis/repository/sample/UserRepository.java#L176

**Comment by kopax** [comment]
This was released in 2.0 correct?

**Comment by easybest** [comment]
> This was released in 2.0 correct?

Already implemented in 2.0

**Comment by kopax** [comment]
What are the requirement for 2.0?

**Comment by easybest** [comment]
> What are the requirement for 2.0?

Spring Boot 2

**Comment by kopax** [comment]
Is there any breaking change with the previous Spring Data Mybatis v1.0.17 or is it safe with it to upgrade?

**Comment by easybest** [comment]
Not compatible with 1.0.17

**Comment by kopax** [comment]
Do you have an upgrade guide please ? :)

**Comment by easybest** [comment]
I think 2.0 will be a better version, taking full advantage of the nature of mybatis

**Comment by kopax** [comment]
Thanks a lot @hatunet, I really appreciate being able using both mybatis and spring. I think this project is awesome. 

Yes, example would be great, but what about a real **documentation** and **upgrade guide** ? Would it be too long to write for us ?

**Comment by easybest** [comment]
documentation @yezhoujie will provide.
