### ISSUE TITLE
Is it possible to override @Entity superclasses annotation ?

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#149]
As in the title, I have a `User` entity annotated with `@Entity(table = "user")`.

I want to create an `Employee` entity annotated with `@Entity(table = "employee")` that extend from user.

There are two cases of figure I need to achieve:

1. `Employee` have a table to extend user table with a `user_id`  reference column. It is simply possible by making `Employee` containg `User` instead of extending it.
1. `Employee` use it's own table for all of it's field. We should be able to override `@Entity(table = "user")` by annotating `Employee.java` class with `@Entity(name = "employee")`.

I did a test for case (2) with the following java code : 

```java
@Data
@Entity(table = "employee")
public class Employee extends User {
    private String employeeDummy;
}
```

## expected

I am expecting to insert `Employee` instance in `employee` table using `EmployeeRepository` 

## result

I al  inserting in `User` and the field `employeeDummy` is ignored in the insert.

What are the possible way to override `@Entity` from superclass ?

**Comment by kopax** [comment]
Possible using a `MappedSuperclass`

```java
@MappedSuperclass
public abstract class GenericEntity {
    private Integer id;
    ...

    public Integer getId() {return id;}
    public void setId(Integer id) {this.id = id;}
}

```

**Comment by easybest** [comment]
you are right
