### ISSUE TITLE
How to create entity with fixed id

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#152]
I want to insert an entity with a fixed entity.
I have tried to use `setId` but it try to update because of `isNew`.

Sorry if I sound a bit dumb but what is the recommended way to insert an entity with fixed id?

**Comment by easybest** [comment]
don't implement Persistable

**Comment by kopax** [comment]
@hatunet I am sorry but I am not understanding: 

My class in question implement from `Identifiable`

    public class AbstractRole  extends AbstractLdapGroupAuthority implements Identifiable<Long>

**Comment by kopax** [comment]
Thank you that make sens.
