### ISSUE TITLE
【请重视】测试实体级联属性时的BUG

### ISSUE THREAD

**Issue by ban584201314** [easybest/spring-data-mybatis#158]
场景一
比如，有一个User实体类，拥有City，Class，Scroll，Grade等级联属性对象，当我给这些属性添加@One2One注解后，新增User时，Grade对象的ID将无法保存至数据库中，如果我将Grade对象放在City对象前面，则Scroll对象的属性ID无法保存
场景二
级联查询时，如果User对象有两个或以上的级联对象，比如Address对象和Age对象都通过user_id一对一关联，当我这两个对象上都使用@JoinColumn(name="user_id",referencedColumnName = "id")后，只能级联出查询其中一个对象

**Comment by easybest** [comment]
2.0 开始不提供自动的级联查询。Spring data Mybatis的本质还是mybatis, 建议使用@Query 充分发挥mybatis的特质。
