### ISSUE TITLE
Springboot2.0 已经正式发布了，请问该项目的2.0版本有具体发布时间吗？

### ISSUE THREAD

**Issue by huyaro** [easybest/spring-data-mybatis#160]
Springboot2.0 已经正式发布了，请问该项目的2.0版本有具体发布时间吗？

**Comment by easybest** [comment]
这个月

**Comment by huyaro** [comment]
说好的这个月呢。。。。

**Comment by kopax** [comment]
any update on this? We'd like to update to springboot 2.0. Would be nice to have a complete example as well.

**Comment by dargoner** [comment]
新版呢，坐等新版

**Comment by suiaing** [comment]
Any release schedule?

I am new to mybatis / github. what should i do if i want to help also?

**Comment by easybest** [comment]
已经发布2.0.0.RELEASE版本 可以支持spring boot 2
