### ISSUE TITLE
Please update the version of "spring-boot2.0"

### ISSUE THREAD

**Issue by liuyang001** [easybest/spring-data-mybatis#162]
Please update the version of "spring-boot2.0"
请为   "spring-boot2.0"  更新版本

**Comment by easybest** [comment]
即将发布

**Comment by kopax** [comment]
Would you make a basic example like before ? 
We still need to be able to use custom xml, multiple data source. Would be nice to have a sample projet or even better, a documentation.

**Comment by liuyang001** [comment]
springboot 2.0 中使用 spring-data-common  版本为 2.0.8  但是作者 使用的  spring-data-common 版本还在 1.13.5  。
