### ISSUE TITLE
findById 报错

### ISSUE THREAD

**Issue by liuyang001** [easybest/spring-data-mybatis#171]
使用   2.0.0.BUILD-SNAPSHOT  新版本  ,   由于在 spring-data 2.0 +  版本中 ， 以前的findOne  , delete(ID  id)  改成了  findById (ID  id) ,  和 deleteById(ID  id)   ， 导致如下报错

Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.ly.mybatisjpa.dao.FkOrgRepository._deleteById

**Comment by heshengchao** [comment]
如果主键（ID）的列名定义与sql 语法一置，也会出现异常，可以考虑对字段做一定的包装！

**Comment by easybest** [comment]
> 如果主键（ID）的列名定义与sql 语法一置，也会出现异常，可以考虑对字段做一定的包装！

Entity怎么写的？
