### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#18]
Dear hatunet,

I have a week or two for testing the module.

I have tried the installation explained in the readme but the project isn't on a repository yet.

I have tried to build the jar with `./mvn install`.

I moved the jar in a spring boot boilerplate project in the `/lib` directory.

I haved tried to import the jar following all of this steps described here : http://stackoverflow.com/questions/20700053/how-to-add-local-jar-file-dependency-to-build-gradle-file

So I am not sure if it's the plugin not working or not finished but adding this doesn't add your classes to my project  :  

    repositories {
        mavenCentral()
        maven { url 'http://repo.spring.io/plugins-release' }
        flatDir {
            dirs 'lib'
        }
    }
    dependencies {
        compile files('lib/spring-data-mybatis-1.0.1.BUILD-SNAPSHOT-sources.jar')
        compile fileTree(dir: 'lib', include: ['*.jar'])
        compile name: 'spring-data-mybatis-1.0.1.BUILD-SNAPSHOT-sources'
    ....

Would be happy to test it if you could tell me how you do for testing it.

**Comment by easybest** [comment]
hi, @kopax 
this version is not the newest ,
I will push the newest code later, 
and maven central repository has passed my application, so you can download the jar from maven central repository next time.

this project will comply with a spring-data standard and be easy used in spring boot project.

maybe complete all things still need 2 or 3 days.

**Comment by kopax** [comment]
Hi @hatunet.

Thanks for all these information, I will wait until you finish and test it straight away.

> this project will comply with a spring-data standard and be easy used in spring boot project.

I have two majors questions about that :

1. Does this plugin will work with spring-hateoas ? (automatically generate link for resources, easy API pagination...)
1. Will you create a test Github repository for demonstrating the spring-data-mybatis ?

Good luck!

**Comment by easybest** [comment]
hi, @kopax 
1. This project can work fine with spring-hateoas.
2. I will create a test repository for demonstrating or integrated test cases.

**Comment by kopax** [comment]
Hi @hatunet any update for the next release ?
