### ISSUE TITLE
扩展自定义mapper xml需要额外的配置吗？

### ISSUE THREAD

**Issue by xyzcoconut** [easybest/spring-data-mybatis#188]
您好，配置了mapper路径以后，repository里写findByXXX，依然是用的方法名生成的查询而不是mapper xml里的sql。mapper xml里的namespace用的是domain类的路径全名。

在issues里搜了一下试着把repository 方法和mapper id改成了_findByXXX，结果启动报错了，No property _findByXXX found for type MyDomain

**Comment by easybest** [comment]
使用@Query注解里面指定
