### ISSUE TITLE
spring-data-mybatis-samples are broken with 2.0.1 release

### ISSUE THREAD

**Issue by tonyfalabella** [easybest/spring-data-mybatis#189]
The https://github.com/hatunet/spring-data-mybatis-samples appear to be broken with the 2.x release.  You no longer have the `org.springframework.data.mybatis.annotations.Entity`, `@OneToMany`, etc. and package names have changed.

**Comment by kopax** [comment]
Indeed, this should be updated. I asked for a migration guide and because we have no clue how to perform this migration, we keep using the old version.

**Comment by kopax** [comment]
Any update on this? 

Could we have a complete working sample with v2?

**Comment by easybest** [comment]
it was moved to https://github.com/easybest/spring-data-mybatis-samples

**Comment by kopax** [comment]
Thank you. I wish you had a documentation at least for entities annotations.

So what is:

- @Embeddable on entity
- `@NamedQuery(name = "Customer.findBySpringDataNamedQuery", query = "select * from t_customer where lastname=?1")` => on entity
- @EmbeddedId

I think I will try your example try to figure out and then spend the time to upgrade parts by parts. If you can give a little help that will definitely increase priority for us.

**Comment by easybest** [comment]
This is the specification for Java Persistence API.
The newest version of Spring Data Mybatis will use the Standard annotations of Java Persistence API.

**Comment by kopax** [comment]
@hatunet I am starting to read the sample. One think that comes in my mind when thinking to migrate my application from v1 to v2:

- It seems that you are not using `beforemappers` anymore while we used it to customize our queries, was this removed in v2 ?

**Comment by easybest** [comment]
you still can use customize mapper.
You can specify path using `mybatis.mapper-locations=classpath*:/org/springframework/data/mybatis/samples/mappers/*Mapper.xml
`

**Comment by kopax** [comment]
## Question 1 - before mappers upgrade

Before we add `public SqlSessionFactoryBean sqlSessionFactory(String[] beforeMapperLocations) throws Exception`,

This allowed us to have such `xml` : 

```xml
<mapper namespace="com.myapp.domain.User">

    <sql id="SELECT_CONDITION_INNER">
        <if test="_condition.startDateTime != null and _condition.endDateTime != null">
            and "date_time" between #{_condition.startDateTime} and #{_condition.endDateTime}
        </if>
    </sql>

</mapper>
```

This was passed to `sqlSessionFactory` on configuration:

```bash
    public SqlSessionFactoryBean sqlSessionFactory(String[] beforeMapperLocations) throws Exception {
        final SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(dataSource());

        String[] beforemappers = (String[]) ArrayUtils.addAll(properties.getBeforeMapperLocations(), beforeMapperLocations);
        if (null != beforemappers && beforemappers.length > 0) {
            Set<Resource> set = new HashSet<>();
            for (String s : beforemappers) {
                Resource[] resources = ResourcePatternUtils.getResourcePatternResolver(this.resourceLoader).getResources(s);
                if (null != resources && resources.length > 0) {
                    set.addAll(Arrays.asList(resources));
                }
            }
            if (!set.isEmpty()) {
                sessionFactory.setMapperLocations(set.toArray(new Resource[set.size()]));
            }
        }
```


In the past, mixing `beforemappers` and `mappers` where causing application crash, are you sure `mybatis.mapper-locations` can handle `SELECT_CONDITION_INNER` beforemapper XML files ? I expect `mapper-locations` to look for full queries.

How can I upgrade my before mapper ?

## Question 2 - DTO  (this question is closely related to question 1)

It seems that you do not have any `CustomerDTO` and you are not using `@Conditions/@Condition` anymore.

How did you remove `DTO`s class and how do we do now if we need to attach some data to an object ? 

How can I upgrade my DTO from mybatis v1 to v2, did they disappear ?

## Question 3 - Sample error: Tweak configuration to get to unambiguous paths!

In your example, going to http://localhost:8080/customers shows:

```bash
 Ambiguous search mapping detected. Both public abstract java.util.List org.springframework.data.mybatis.samples.repository.CustomerRepository.findTop2CustomersBy(org.springframework.data.domain.Sort) and public abstract org.springframework.data.domain.Slice org.springframework.data.mybatis.samples.repository.CustomerRepository.findTop2CustomersBy(org.springframework.data.domain.Pageable) are mapped to /findTop2CustomersBy! Tweak configuration to get to unambiguous paths!
	at org.springframework.data.rest.core.mapping.SearchResourceMappings.<init>(SearchResourceMappings.java:62) ~[spring-data-rest-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
```

How can we fix this?

**Comment by easybest** [comment]
@kopax r u want to keep some `embedded point` (such `SELECT_CONDITION_INNER `) in v2 @Condition query?
I think there's better ways to get the goal of `Dynamic conditional query`.

Considering compatibility, I will still keep the features in V2, but it will be marked `@Deprecated`.

To solve your problems more efficiently, you can share your project (part but able to function properly) to me, and I can migrate it from v1 to v2 directly.

**Comment by easybest** [comment]
@kopax suggest you open new issue, otherwise I will lost some information from you if you just commit in closed issues.
