### ISSUE TITLE
您好，请问新版本不支持@OneToMany等注解了，非字段映射的属性需要使用，如果不加@Transient的话会报错，加了@Transient注解的话属性又不能映射属性值，那mybatis映射文件中一对多、或者多对多如何处理呢？

### ISSUE THREAD

**Issue by world9781** [easybest/spring-data-mybatis#191]
您好，请问新版本不支持@OneToMany等注解了，非字段映射的属性需要使用，如果不加@Transient的话会报错，加了@Transient注解的话属性又不能映射属性值，那mybatis映射文件中一对多、或者多对多如何处理呢？谢谢！

**Comment by yezhoujie** [comment]
这个现在我们推荐的方式是自己写resultMap， 映射到你那个domain上，在配合@Query, 或者在一个事务内查询两次。通常使用第二种

**Comment by world9781** [comment]
您的意思是说有这两种方式吗：
第一种：首先mabatis映射文件中写resultMap映射那个属性到对应的实体，然后再配合@query注解使用
第二种：一个事务中查询两次，两个表分开单独查询

**Comment by yezhoujie** [comment]
> 您的意思是说有这两种方式吗：
> 第一种：首先mabatis映射文件中写resultMap映射那个属性到对应的实体，然后再配合@query注解使用
> 第二种：一个事务中查询两次，两个表分开单独查询

对的，第二种简单一点，也比较灵活，其实@OneToMany底层也是查两次，只要事务你控制好就行

**Comment by world9781** [comment]
第一种方式之前测试过，@Entity、@Transient与mybatis中的resultMap互相矛盾，无法把值映射到那个属性，不是报 “No typehandler found for property” 这个错误，就是属性值总是null
第二种方式，感觉有的时候用多表查询更合适一点。

对于这个问题，后面的升级会不会解决这个问题呢？比如再增加个注解类型，这个注解类型不用映射到字段，但是可以通过resultMap去赋值，mybatis plus中有这样一个类似的注解类型

**Comment by yezhoujie** [comment]
> 第一种方式之前测试过，@entity、@transient与mybatis中的resultMap互相矛盾，无法把值映射到那个属性，不是报 “No typehandler found for property” 这个错误，就是属性值总是null
> 第二种方式，感觉有的时候用多表查询更合适一点。
> 
> 对于这个问题，后面的升级会不会解决这个问题呢？比如再增加个注解类型，这个注解类型不用映射到字段，但是可以通过resultMap去赋值，mybatis plus中有这样一个类似的注解类型

@transient 应该和resultMap 没有关系，只有自动生成sql的时候才会有关联，可以把你的domain 代码和repository代码发上来看一下。

**Comment by world9781** [comment]
> > 第一种方式之前测试过，@entity、@transient与mybatis中的resultMap互相矛盾，无法把值映射到那个属性，不是报 “No typehandler found for property” 这个错误，就是属性值总是null
> > 第二种方式，感觉有的时候用多表查询更合适一点。
> > 对于这个问题，后面的升级会不会解决这个问题呢？比如再增加个注解类型，这个注解类型不用映射到字段，但是可以通过resultMap去赋值，mybatis plus中有这样一个类似的注解类型
> 
> @transient 应该和resultMap 没有关系，只有自动生成sql的时候才会有关联，可以把你的domain 代码和repository代码发上来看一下。
![github1](https://user-images.githubusercontent.com/8512106/57495457-c2fc0000-7300-11e9-9ad3-01ce35081504.png)
![github2](https://user-images.githubusercontent.com/8512106/57495466-c8594a80-7300-11e9-9abd-833ca967f611.png)

1、按照图中的写，Role、Menu非表字段属性值为null
2、Role、Menu非表字段属性如果不用@transient注解的话，直接报 “No typehandler found for property” 错误

总结：这样的话感觉有点互相矛盾了，这问题导致mybatis映射文件中不能写多表联合查询语句了，如果只能在mybatis映射文件中写单表查询语句的话，那mybatis的优势就不明显了，这样就跟hibernate模式的jpa区别不大了。

**Comment by yezhoujie** [comment]
新的版本即将上线，敬请期待

**Comment by world9781** [comment]
> 新的版本即将上线，敬请期待

非常感谢您的解答，很期待新的版本，新的版本会解决（多表联合查询写在xml映射文件中，且非映射字段属性值不为null问题）这个问题吗？大概什么时间上线呢，新版本的有什么新的主要功能呢，可以提前分享下吗，谢谢！

**Comment by world9781** [comment]
> @anuolifeng1 在你的repository 的那个方法上方要加一个注解 @ResultMap("roleMenuResultMap")，这样程序才知道你用的是这个resultMap，不然就会使用默认自动生成的”__result_map“来映射结果，保留@transient，以确保其他方法能顺利映射

谢谢！这是一种解决的方案，我更加的喜欢写在xml映射文件中，这样直接调整xml，不用调整程序代码了。

**Comment by yezhoujie** [comment]
@anuolifeng1 如果你想把sql 和 resultMap 写在xml 中，只要在@Query 里指定statemet= xml 中的queryID即可， xml 中的namespace 为 repository 的全路径地址

**Comment by world9781** [comment]
> @anuolifeng1 如果你想把sql 和 resultMap 写在xml 中，只要在@query 里指定statemet= xml 中的queryID即可， xml 中的namespace 为 repository 的全路径地址

@Query中不想写sql，感觉调整sql语句总是去调整对应的java源代码部分不是很好！

**Comment by yezhoujie** [comment]
@anuolifeng1 我上面提到的方式，不需要你在@query 中写sql, sql 还是写在xml 文件中， @query 中只要指定一些 queryID 就可以了

**Comment by world9781** [comment]
> @anuolifeng1 我上面提到的方式，不需要你在@query 中写sql, sql 还是写在xml 文件中， @query 中只要指定一些 queryID 就可以了

跟您确定下，整个是这样用吗，如果有问题请您多多指点，比如：

@ResultMap("roleMenuResultMap")//roleMenuResultMap为xml映射文件中的ResultMap
@Query(statement = "findAllByRoleId") //findAllByRoleId为xml映射文件中的queryID（@Query一般不都是直接写sql语句吗）
List<RoleMenu> findAllByRoleId(Long roleId);//这个方法为对应DAO中的方法

**Comment by yezhoujie** [comment]
@anuolifeng1 请参考 https://github.com/hatunet/spring-data-mybatis/blob/0bebe40ba74d807f621dc7b46380c2abc4b154df/spring-data-mybatis/src/test/resources/mapper/user.xml 和 https://github.com/hatunet/spring-data-mybatis/blob/c224fb9e331dee5a463e795b37bc7e597d87fb17/spring-data-mybatis/src/test/java/org/springframework/data/mybatis/repository/sample/UserRepository.java 中的“search_by_email”例子（例子中的resultMap 需要自己重新在xml 中定义）

**Comment by anuolifeng1** [comment]
> @anuolifeng1 请参考 https://github.com/hatunet/spring-data-mybatis/blob/0bebe40ba74d807f621dc7b46380c2abc4b154df/spring-data-mybatis/src/test/resources/mapper/user.xml 和 https://github.com/hatunet/spring-data-mybatis/blob/c224fb9e331dee5a463e795b37bc7e597d87fb17/spring-data-mybatis/src/test/java/org/springframework/data/mybatis/repository/sample/UserRepository.java 中的“search_by_email”例子（例子中的resultMap 需要自己重新在xml 中定义）

好的，但是现在在application.yml中配置mybatis的mapper-locations时报错了，之后加上@MapperScan后又会报其他错误，具体详情这个链接有详细说明，https://github.com/hatunet/spring-data-mybatis/issues/197，我现在用的spring boot 版本是2.1.4，会不会跟spring boot的版本有关系呢

**Comment by world9781** [comment]
> @anuolifeng1 请参考 https://github.com/hatunet/spring-data-mybatis/blob/0bebe40ba74d807f621dc7b46380c2abc4b154df/spring-data-mybatis/src/test/resources/mapper/user.xml 和 https://github.com/hatunet/spring-data-mybatis/blob/c224fb9e331dee5a463e795b37bc7e597d87fb17/spring-data-mybatis/src/test/java/org/springframework/data/mybatis/repository/sample/UserRepository.java 中的“search_by_email”例子（例子中的resultMap 需要自己重新在xml 中定义）

最终测试结果如下：

问题很奇怪，下面3种配置导致的问题不一样

1、第一种配置如下：这个时候开启@ResultMap、@query这两个注解不报错，但是调用Dao接口的方法查询不到数据
mybatis:
mapper-locations: classpath*:mapping/**/Dao.xml

2、第二种配置如下：这个时候开启@ResultMap、@query这两个注解直接报错 "Error querying database. Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.xxx.module.system.dao.RoleMenuDao.findAllByRoleId"；如果不开启这两个注解，可以调用Dao接口方法查出数据
spring:
data:
mybatis:
mapper-Locations: mapper-locations: classpath*:mapping/**/Dao.xml
3、如果application.yml中不配置mybatis的mapper-locations属性，可以调用Dao接口方法查出数据；但是如果开启@ResultMap、@query这两个注解直接报错 "Error querying database. Cause: java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.xxx.module.system.dao.RoleMenuDao.findAllByRoleId"

总结：@ResultMap、@query这两个注解感觉还是有些问题

**Comment by world9781** [comment]
这两天抽时间又测试了下，问题跟之前的测试结果一样，可以肯定的是mapper.xml形式的映射文件可以找到没有问题，问题还是出在@ResultMap、@query这两个注解上，以下的使用方式findAllByRoleId查询不到任何数据

@ResultMap(value = "roleMenuResultMap")
@Query(statement = "findAllByRoleId")    
List<RoleMenu> findAllByRoleId(Long roleId);


这次也测试了下以下的这种方式，结果也不能使用，问题跟上面的一样

@ResultMap(value = "roleMenuResultMap")
@Query(value = "SELECT rm.id AS rm_id, rm.role_id AS rm_role_id, rm.menu_id AS rm_menu_id, r.id AS r_id, r.role_identifier AS r_role_identifier, m.id AS m_id, m.menu_href AS m_menu_href FROM xxx_sys_role_menu rm LEFT JOIN xxx_sys_role r on r.id = rm.role_id LEFT JOIN xxx_sys_menu m on rm.menu_id = m.id WHERE rm.role_id = ?1")  
List<RoleMenu> findAllByRoleId(Long roleId);


如果不加@ResultMap、@query这个两个注解，是可以查询到数据的，但是这样的话，就达不到想要@transient注解的非字段映射属性可以赋值的功能了。按照你们提供的方式是不能解决这个问题的。新版本不支持@OneToMany等注解了，多表联合查询又不能很好的使用association、collection映射其他类的属性，如果这样使用起来就非常的不方便了，感觉这个问题有点严重啊，总不能什么地方都是单表查询吧！如果想要使用多表联合查询还得增加一层来做多表查询结果的映射（需要增加很多根本不需要的类）

**Comment by easybest** [comment]
已经已经找到一种好的方法实现 平衡关联查询了。https://github.com/hatunet/spring-data-mybatis/milestone/12 将在这个里程碑版本发布提供。

**Comment by world9781** [comment]
> 已经已经找到一种好的方法实现 平衡关联查询了。https://github.com/hatunet/spring-data-mybatis/milestone/12 将在这个里程碑版本发布提供。

这个版本什么时间发布呢？

**Comment by world9781** [comment]
> > 已经已经找到一种好的方法实现 平衡关联查询了。https://github.com/hatunet/spring-data-mybatis/milestone/12 将在这个里程碑版本发布提供。
> 
> 这个版本什么时间发布呢？

建议考虑支持mapper.xml映射文件中多表联合查询进行关联类的association、collection映射方式，感觉这种方式更加的灵活，优化sql语句也更加的方便处理

**Comment by easybest** [comment]
> > > 已经已经找到一种好的方法实现 平衡关联查询了。https://github.com/hatunet/spring-data-mybatis/milestone/12 将在这个里程碑版本发布提供。
> > 
> > 
> > 这个版本什么时间发布呢？
> 
> 建议考虑支持mapper.xml映射文件中多表联合查询进行关联类的association、collection映射方式，感觉这种方式更加的灵活，优化sql语句也更加的方便处理

新版本就是这么实现的

**Comment by easybest** [comment]
> > 已经已经找到一种好的方法实现 平衡关联查询了。https://github.com/hatunet/spring-data-mybatis/milestone/12 将在这个里程碑版本发布提供。
> 
> 这个版本什么时间发布呢？

预计本月能发布

**Comment by dargoner** [comment]
> > > 已经已经找到一种好的方法实现 平衡关联查询了。https://github.com/hatunet/spring-data-mybatis/milestone/12 将在这个里程碑版本发布提供。
> > 
> > 
> > 这个版本什么时间发布呢？
> 
> 预计本月能发布

五月过去了，六月还发版吗

**Comment by easybest** [comment]
> > > > 已经已经找到一种好的方法实现 平衡关联查询了。https://github.com/hatunet/spring-data-mybatis/milestone/12 将在这个里程碑版本发布提供。
> > > 
> > > 
> > > 这个版本什么时间发布呢？
> > 
> > 
> > 预计本月能发布
> 
> 五月过去了，六月还发版吗

要发的。

**Comment by dargoner** [comment]
啥时更新啊，功能等急用，黄花菜都要快凉了

**Comment by easybest** [comment]
已经支持
