### ISSUE TITLE
source

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#2]
Hi, I am currently trying to work on a spring-data-mybatis module as well very actively (everyday).

I am trying to make the jclagache plugin compatible with the latest spring version but it's a bit painful to got it work.

I've seen you've just created this 4 days ago ? Do you mind if we work together ?

**Comment by easybest** [comment]
hi, 
The module is nearing completion and have pushed the newest code. 
You can review the code first and discuss with me.
Welcome to work together.
