### ISSUE TITLE
建议支持国产达梦数据库的方言

### ISSUE THREAD

**Issue by dargoner** [easybest/spring-data-mybatis#201]
现在数据国产化的要求很紧迫，考虑支持点国产数据库，如达梦数据库。目前测试下来达梦方言跟Oracle一样。建议框架下个发版时直接增加进去，免的项目再自行扩展

**Comment by easybest** [comment]
请给出参考资料

**Comment by dargoner** [comment]
https://gitee.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-extension/src/main/java/com/baomidou/mybatisplus/extension/plugins/pagination/dialects/DmDialect.java

**Comment by easybest** [comment]
#220
