### ISSUE TITLE
按实体属性筛选是不是没有完成？

### ISSUE THREAD

**Issue by zt1820057934** [easybest/spring-data-mybatis#207]
请问 比如findAll(Example example),findAll(X condition),countAll(X condition)这些筛选功能怎么没有用呢？比较推荐的筛选和分页应该怎么实现？
GroupUser criteria = new GroupUser();
criteria.setStudioId(it.getStudioId());
criteria.setGroupId(it.getId());
dto.setGroupName(it.getName());
long num = this.groupUserRepository.countAll(criteria);

**Comment by yezhoujie** [comment]
请在你的entity 实体类的字段上添加@Condition, 这个字段有值时才会进行筛选。
![image](https://user-images.githubusercontent.com/25244187/64962978-69837f00-d866-11e9-9713-67ec42be595f.png)

**Comment by zt1820057934** [comment]
感谢大牛及时回复，非常感谢，以前一直写的xml，JPA不太适应
