### ISSUE TITLE
中文版的readme中 springboot项目中，依赖本项目的artifactId 是否写错了

### ISSUE THREAD

**Issue by wxz0107** [easybest/spring-data-mybatis#230]
使用 Spring Boot
通过maven引入:

<dependency>
    <groupId>io.easybest</groupId>
    <artifactId>spring-boot-starter-data-mybatis</artifactId>
    <version>2.0.1.RELEASE</version>
</dependency>

应该是spring-data-mybatis-boot-starter

**Comment by easybest** [comment]
是的。谢谢
