### ISSUE TITLE
1.0.3 Test broken

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#32]
From a clone repository
Running

     mvn install

Results :

Failed tests: 
  RoleSimpleRepositoryTests.testCount:135 expected:<4> but was:<5>
  RoleSimpleRepositoryTests.testFindAll:114 expected:<4> but was:<5>
  RoleSimpleRepositoryTests.testFindByPage:184 expected:<4> but was:<5>
  RoleSimpleRepositoryTests.testFindBySort:175 expected:<ROLE_assistant> but was:<ROLE_admin>

I did a small Pull requests here :   #24

**Comment by easybest** [comment]
hi, @kopax 
what's database engine r u use?

all test cases were passed at [https://travis-ci.org/hatunet/spring-data-mybatis/jobs/182253300](https://travis-ci.org/hatunet/spring-data-mybatis/jobs/182253300)

**Comment by easybest** [comment]
maybe you haven't clean your table in db.

**Comment by kopax** [comment]
I am using mariadb. I have the feeling that for the test it use the embedded h2 database.

**Comment by easybest** [comment]
I test all test cases using h2, mysql, oracle and sql server, all of them were passed.

**Comment by easybest** [comment]
It used embedded h2 database in travis-ci 's integration test.

**Comment by kopax** [comment]
It also use embedded h2 database when I run `mvn install`.

I have never used h2 database before, but I can assume it from the output log when I run the `mvn install` cmd

```ruby
22:37:49.973 [main] INFO  o.s.j.d.e.EmbeddedDatabaseFactory - Starting embedded database: url='jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false', username='sa'
```

This can be test in 5 steps and can give you a build:

1. `$ git clone git@github.com:hatunet/spring-data-mybatis.git`
2. `$ cd spring-data-mybatis`
3. `$ mvn install` _<== fail_
4. `$ rm src/test/java/org/springframework/data/mybatis/repository/RoleSimpleRepositoryTests.java`
5. `$ mvn install` _<== succeed_

You can see the complete logs here : 

https://codetidy.com/9784/

**Comment by easybest** [comment]
But I did not find this error.
I will further investigation tomorrow

**Comment by kopax** [comment]
FYI, I have the same problem with 1.0.4.RELEASE. Did you investigate a bit on this ?
