### ISSUE TITLE
Supported spring-data annotations by this plugin

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#37]
Can I assume these spring-data annotations work well with this plugins ?

- @Version : Should add ETAG to response header using specified @Column, should be incremented on update.
- @CreatedDate : Should update with current timestamp when inserting
- @LastModifiedDate : Should update with current timestamp when updating
- @CreatedBy : Should update with principal when inserting
- @LastModifiedBy : Should update with principal when updating

__Edit__

So far I have tested

with success:

- @OneToOne(referencedColumnName = "BANANA_ID")
- @JdbcType(VARCHAR)
- @Column(name = "PRINCIPAL_ADDRESS")
- @Entity(table = "BANANA")
- @NotNull

with failure:

- @Version: correctly add etag to response header but does not be incremented on insert neither update

When I try to access the data rest controller with an entity created without a setVersion(1)
```ruby
/rest/companies/1 reached end of additional filter chain; proceeding with original chain
null
java.lang.NullPointerException: null
	at org.springframework.data.rest.webmvc.support.ETag.getVersionInformation(ETag.java:192)
	at org.springframework.data.rest.webmvc.support.ETag.from(ETag.java:76)
```
- @CreatedDate : Doesn't update the datetime
- @LastModifiedDate : Doesn't update the datetime

todo test: 

- @LastModifiedBy : Should update with principal when updating
- @CreatedBy : Should update with principal when inserting

**Comment by easybest** [comment]
@Version  @CreatedDate @LastModifiedDate will be support in 1.0.6

**Comment by kopax** [comment]
Why does the `@CreatedBy` `@LastModifiedBy` are not in `1.0.6` ? Will it be supported at some point ?
I've seen you did some push about annotations, is it ready for testing ? :) ?

**Comment by easybest** [comment]
It will be completed in 1.0.6, now it's under my testing, but code have not been pushed to the repository.

**Comment by easybest** [comment]
1.0.6 version will be released in this week.
