### ISSUE TITLE
Implement method with Iterable and List as in JPA 

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#38]
Would be nice to have repository method aliased to get Collection as `List<>` in addition of `Iterable<>`. 

I thought it was already implemented in spring-data but it seems to be spring-data-jpa specific.

http://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html#findAll--

**Comment by easybest** [comment]
in spring data commons, really used Iterable<> 

but spring-data-jpa used List<>

I'm thinking about which one is better

**Comment by kopax** [comment]
I vote for both.

**Comment by easybest** [comment]
I decided to use List,
I think List is better , because it's extend Iterable
