### ISSUE TITLE
Support MySQL, Oracle, Sql Server, H2, etc

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#44]
In a futur release, do you planify to have a postgresql support ?

**Comment by easybest** [comment]
yes，it will be support in 1.0.6

**Comment by easybest** [comment]
see #46

**Comment by kopax** [comment]
Thanks, I am testing it.
Can't wait to see https://github.com/hatunet/spring-data-mybatis/issues/37.

**Comment by easybest** [comment]
`Thanks, I am testing it.
Can't wait to see https://github.com/hatunet/spring-data-mybatis/issues/37.`

it will be OK in 1.0.6, and it's under testing.
