### ISSUE TITLE
support @CreatedDate and @LastModifiedDate to audit entity automatically

### ISSUE THREAD

**Issue by easybest** [easybest/spring-data-mybatis#53]
```java
@CreatedDate
    protected Date createdDate;


    @LastModifiedDate
    protected Date lastModifiedDate;
```

**Comment by easybest** [comment]
ass to #37

**Comment by kopax** [comment]
I don't know if it's completely out of your spec or not.
I know it is not on the specs of spring-data, but would it be complicated to support java.util.Instant type for @CreationDate @LastModifiedDate ? Juste because it is more correct to store it as a Timestamp than a Date.
