### ISSUE TITLE
Support Instant for @CreatedDate and @LastModifiedDate

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#65]
I was trying to setup my database for theses annotations and 

        Caused by: java.lang.IllegalArgumentException: now we can not support java.time.Instant for org.springframework.data.annotation.CreatedDate

It sounds like the library still uses the old date apis when there are better replacements available (310).

I did the following annotations

```java
@CreatedDate
@NotNull
@JdbcType(TIMESTAMP)
@Column(name = "CREATION_DATETIME")
private Instant creationDateTime;
```

I could use `timestamp` jdbcType and `Date` so it will probably work, but date is not the best options.

Ideally we would use `Instant` (java) and `timestamp` (jdbcType) as in my example.

The way it is made force us to use `Date` : 

https://github.com/hatunet/spring-data-mybatis/blob/3c24082f923d758dbb0da4382f9adc09854ea871/src/main/java/org/springframework/data/mybatis/repository/support/MybatisMetamodelEntityInformation.java#L98

`DateTime` is a joda class. they support that. but 310 replaces joda, though even in joda, `Instant`, not `DateTime`, is the right type.

It's probably the spring-data spec, I fixed it using getter and setter using Instant, but it would be nice to also support Instant as java type.

**Comment by easybest** [comment]
see #66 

now you can customize any type of Date

**Comment by easybest** [comment]
try to use AuditDateAware<T>
but now you should use version : 1.0.8.BUILD-SNAPSHOT

**Comment by easybest** [comment]
add a spring bean like this : 

```java
@Bean
    public AuditDateAware<Instant> auditDateAware() {
        return new AuditDateAware<Instant>() {
            @Override
            public Instant getCurrentDate() {
                return new Instant();
            }
        };
    }
```

**Comment by kopax** [comment]
I haven't created the spring bean that's probably why.
I'll wait till #69 is corrected because I won't be able to start my app until then and I have a try and test for all the new features since 1.0.5 to now.

**Comment by easybest** [comment]
I will fix it now
