### ISSUE TITLE
Escape character should be added to PGSQL queries (bis)

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#69]
Did you noticed #48 as not been completed entirely ? I have the feeling not. (sorry for duplicate)

**Comment by easybest** [comment]
I have found the reason.

you can use 1.0.8.BUILD-SNAPSHOT and have a try again.

**Comment by kopax** [comment]
Strange, I've build from master a 1.0.8 snapshot, I've checked before if the build contains that modification

    builder.append(dialect.wrapColumnName(association.getJoinColumnName())).append(",");

 and I still have this error : 

```bash
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: column "company_ID" of relation "CUSTOMER" does not exist
  Position: 150
### The error may involve com.domain.customerManagement.Customer._insert-Inline
### The error occurred while setting parameters
### SQL: insert into "CUSTOMER"("ACTIVE","CREATION_DATETIME","FIRST_NAME","LAST_NAME","MODIFICATION_DATETIME","PRINCIPAL_PHONE","PRINCIPAL_ADDRESS","VERSION","company_ID") values(?,?,?,?,?,?,?,?,?)
```

So now it is escaped with double quote, but the table table name is still a lower case

**Comment by easybest** [comment]
```java
@JdbcType(BIGINT)
@OneToOne(referencedColumnName = "COMPANY_ID")
@NotNull
private Company company;
```

change to :

```java
@OneToOne
@JoinColumn(name = "COMPANY_ID")
@NotNull
private Company company;
```

**Comment by easybest** [comment]
Is it OK now ? @kopax

**Comment by kopax** [comment]
I've just tested out but not in depth, It is now working without any hassle. 

Thank you for that,

At the mean time, merry x-mas && happy new year
