### ISSUE TITLE
calling repository.deleteAll should reset Auto Increment in postgresql

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#73]
I am not sure if it's an expected behavior, but with mariadb, calling `repository.deleteAll()` was also resetting the auto incrementation to 1.

http://stackoverflow.com/questions/5342440/reset-auto-increment-counter-in-postgres

This can be achieved manually, would be nice to implement it in `deleteAll()`

**Comment by easybest** [comment]
deleteAll just execute SQL :
```sql
truncate Table
```

resetting auto_increment  to 1 is database's behavior, this module can not resolve this problem.
