### ISSUE TITLE
Question about usage and extends using xml files

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#75]
Considering the following xml custom mapper for a `Manager` entity : 

```xml
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.repository.userManagement.ManagerRepository">
    <!--<cache />-->

    <!-- Is it possible to reuse the spring-data-mybatis instead of writing this one -->
    <resultMap id="managerResultMap" type="com.domain.userManagement.Manager">
        <id property="id" column="id" />
        <result property="login" column="login" jdbcType="VARCHAR" javaType="string" />
        <result property="roleList" column="roleList" jdbcType="BLOB" typeHandler="com.typeHandler.RoleListTypeHandler" />
        <result property="password" column="password" jdbcType="VARCHAR" javaType="string" />
        <result property="version" column="version" jdbcType="BIGINT" javaType="long" />
        <result property="active" column="active" jdbcType="BOOLEAN" javaType="boolean" />
        <result property="creationDateTime" column="creationDateTime" jdbcType="DATE" typeHandler="com.typeHandler.DateTimeTypeHandler" />
        <result property="modificationDateTime" column="modificationDateTime" jdbcType="DATE" typeHandler="com.typeHandler.DateTimeTypeHandler" />
    </resultMap>

    <!-- Is it possible to reuse the spring-data-mybatis instead of writing this one -->
    <sql id="getManagerSelect">
        SELECT
            manager.`ID` as 'id',
            manager.`LOGIN` as 'login',
            manager.`ROLES` as 'roleList',
            manager.`PASSWORD` as 'password',
            manager.`VERSION` as 'version',
            manager.`CREATION_DATETIME` as 'creationDateTime',
            manager.`MODIFICATION_DATETIME` as 'modificationDateTime',
            manager.`ACTIVE` as 'active'
    </sql>

    <!-- Is it possible to reuse the spring-data-mybatis instead of writing this one -->
    <sql id="getManagerFrom">
        FROM
          `MANAGER` manager
    </sql>

    <!-- So it will be possible to write small queries like this -->
    <select id="find" resultType="com.domain.userManagement.Manager" parameterType="Long">
        <include refid="getManagerSelect" />
        <include refid="getManagerFrom" />
        <if test="pk">
          WHERE manager.`ID` = #{pk.value}
        </if>
    </select>
    
    <!-- This is a delete override only for that entity -->
    <delete id="delete" parameterType="com.domain.userManagement.Manager">
        UPDATE
         `MANAGER`
        SET
          `ACTIVE` = 1
        <if test="pk">
          WHERE `ID` = #{pk.value}
        </if>
    </delete>

</mapper>
```

I would like to know __if it is possible to__ : 

1. override default `delete` query for a single entity like in this xml
1. how is it possible to change `repository.delete()` and `repository.deleteAll()` for doing it on all entities
1. reuse the `spring-data-mybatis` generated `resultMap` so I don't need to maintain my own (for example by knowing in advance the resultMap id.

Note: 
 		
I really wouldn't do that. That would radically change the contract of these two methods but I need to know if these extends can be set up.

**Comment by easybest** [comment]
hi @kopax , thanks for your profound questions.

1.  it supports override default delete query for a single entity, you should add your custom mapper when create SqlSessionFactory, and use entity's class name as mapper's namespace , and define a delete statement with id "_deleteById" , because I have judged the statement is exist before creating default query.
```java
if (!isStatementExist("_deleteById")) {
            buildDeleteById(builder);
        }
```

2. have a look at [http://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.custom-behaviour-for-all-repositories](http://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.custom-behaviour-for-all-repositories)

if you have further question, you can ask me.

3. tell you a small tip : set "org.springframework.data.mybatis" logger level to debug , you can find the default mapper on the console.

**Comment by easybest** [comment]
because of poor document now ( I am writing hardly ),  
you can hardly find out some features.

So if you can provide me some runnable code , I will resolve your questions more effectively.

**Comment by kopax** [comment]
1. OK
2. OK
3. Thanks

For 3 could you provide me an example for let's say.

I want to implement a select with a custom "WHERE"

```sql
SELECT
...
FROM
...
WHERE 
    us_reg_date between '2000-07-05'
AND
    DATE_ADD('2011-11-10',INTERVAL 1 DAY)
```

It will be nice to just be able to just define the WHERE part

```xml
    <select id="selectStepDay" resultType="com.entityA" parameterType="DATE">
        <include refid="_selectEntityA" /> <!-- if you generate these for your select, it should be reusable isn't it ?-->
        <include refid="_fromEntityA" /> <!-- if you generate these for your select, it should be reusable isn't it ?-->
        WHERE 
          us_reg_date between '2000-07-05'
        AND
          DATE_ADD(#value#,INTERVAL 1 DAY)
    </select>
```

I think I don't need the `resultMap` if I use the `resultType` I assume this will be handled in your module.
I have seen some code in your module that generate a mapping, is it a resultMap and if it is, is it in the globalScope ? Would it be more accurate to use `resultMap` over `resultType` ?

If you generate the _selectEntityA in an xml markup `<sql id=_select"+perisistentEntity.getClass()+">` and same for _fromEntityA, we might be able to reuse them from the global scope of this entity is it correct ?
this way we could rewrite override it in our own file if we need to. It give's flexibility.

It would be interesting to use the builder for really creating the xml file and see how this could be used with our custom mappers.

**Comment by easybest** [comment]
see https://github.com/hatunet/spring-data-mybatis-testing/tree/extendxml
