### ISSUE TITLE
Add automatic conversion of Boolean to false if null

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#76]
I know it's not the most important right now but I would like just to open the question

I have a case where I have the following __postgresql__ column : 

```sql
  "ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
```

In my entity I have 

```java
@JdbcType(BOOLEAN)
@Column(name = "ACTIVE")
@NotNull
private Boolean active;
```

When I try to save this entity, `spring-data-mybatis` try to insert with null values and it generate an error.

I have annotated the JdbcType so the ORM should be aware of the data type, if `active` is null it could directly insert `false` instead of trying to insert a non eligible `null`.

**Comment by easybest** [comment]
you can do like this : 

```java
@JdbcType(BOOLEAN)
@Column(name = "ACTIVE")
@NotNull
private Boolean active = true; // set the default value
```

**Comment by kopax** [comment]
This is what I have done, I was thinking of an ORM feature with column type conversion.

**Comment by easybest** [comment]
otherwise , can create a TypeHandler to convert null-boolean to false or right

**Comment by kopax** [comment]
I'll close this, TypeHandler is a good idea but there is no real benefits. It's not very important, would be nice if postgresql could take care of that. I'll just keep it like in your code example.
