### ISSUE TITLE
how to insert new entity with a fixed id

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#83]
I need to have something like this do the insertion

    this.repository.save(new Entity(1L, 'test'));

The save will fail because it's a new entity and not an update.

I know there is a check on the isNew() method, I just want to know how do you manage these kind of insert properly.

Thanks in advance :)

**Comment by easybest** [comment]
now MybatisRepository has added two new method : 
```java
    <S extends T> S insert(S entity);

    <S extends T> S update(S entity);
```

So you can more accurately control your operations.

In the absence of a better way, you can use this method.
