### ISSUE TITLE
@OneToMany doesn't select join column because of missing join statement

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#84]
# annotation @OneToMany doesn't join column

It appear the __@OneToMany__ association doesn't work as expected.

## version
I am using [commit](https://github.com/hatunet/spring-data-mybatis/commit/f22774e0a6a9057e5909caeba9a2cde55038227a).

This is how I did the join table mapping, in `SiteService.java` :

```java
@JdbcType(BIGINT)
@OneToMany
@JoinTable(name = "SITE_FUNCTION")
@JoinColumn(name = "SITE_SERVICE_ID")
@NotNull
private List<SiteFunction> siteFunctionList;
```

## Result

Produce an empty array for `siteFunctionList` 

## Expected result

Produce an array using database data for  `siteFunctionList` 

The select method appear to not add any jointure for this table.

(but @ManyToOne association seems to work fine so far.)
The xml generated render an empty `  <sql id="SELECT_CONDITION_INNER"></sql>`

What is it use for ?

There is this generated for the mapping by the annotations: 

```xml
        <collection property="siteFunctionList" ofType="com.domain.security.SiteFunction">
            <id property="id" column="siteFunctionList.id" javaType="java.lang.Long" jdbcType="BIGINT"/>
            <result property="messageId" column="siteFunctionList.messageId" javaType="java.lang.String"
                    jdbcType="VARCHAR"/>
            <result property="name" column="siteFunctionList.name" javaType="java.lang.String" jdbcType="VARCHAR"/>
        </collection>
```

But nothing for selecting the field.

**Comment by kopax** [comment]
I also wonder, in this scenario, is there any way for me to just rewrite or add some extra xml in my mappers folder in order to complete/repair the mapping ?

That would be a good information to know.

**Comment by kopax** [comment]
Hi @hatunet any update on this ?

**Comment by kopax** [comment]
I have upgraded to spring-boot 1.5.1.RELEASE and now how spring-data-commons 1.13.RELEASE according to #98 

I was able to start without my error but it seems the one to many have some "case" and mapping issues.

## @OneToMany

__spring-data-mybatis commit version : 3b6fba0__ 

Test repository available [here](https://github.com/kopax/spring-data-mybatis-testing)

    git clone git@github.com:kopax/spring-data-mybatis-testing.git
    git checkout onetomany
    ./gradlew build --info && java -jar build/libs/spring-data-mybatis-testing-0.1.0.war
    
### Test

    curl http://localhost:8080/siteServices
    
### Expected

HTTP 200
    
### Result

    Thu Feb 02 19:14:48 ICT 2017
    There was an unexpected error (type=Internal Server Error, status=500).
    ### Error querying database. Cause: org.h2.jdbc.JdbcSQLException: Column "SITE_FUNCTION.SITE_FUNCTION_ID" not found; SQL statement: select "siteService".id as "id","siteService".NAME as "name","siteService.siteFunctionList".id as "siteFunctionList.id","siteService.siteFunctionList".NAME as "siteFunctionList.name","siteService.siteFunctionList".SITE_SERVICE_ID as "siteFunctionList.siteService.id" from SITE_SERVICE "siteService" left outer join SITE_FUNCTION on SITE_FUNCTION.SITE_SERVICE_id="siteService".id left outer join SITE_FUNCTION "siteService.siteFunctionList" on SITE_FUNCTION.SITE_FUNCTION_id="siteService.siteFunctionList".id [42122-193] ### The error may exist in org.springframework.data.mybatis.samples.security.SiteService_auto_generate.xml ### The error may involve org.springframework.data.mybatis.samples.security.SiteService._findAll ### The error occurred while executing a query ### SQL: select "siteService".id as "id","siteService".NAME as "name","siteService.siteFunctionList".id as "siteFunctionList.id","siteService.siteFunctionList".NAME as "siteFunctionList.name","siteService.siteFunctionList".SITE_SERVICE_ID as "siteFunctionList.siteService.id" from SITE_SERVICE "siteService" left outer join SITE_FUNCTION on SITE_FUNCTION.SITE_SERVICE_id="siteService".id left outer join SITE_FUNCTION "siteService.siteFunctionList" on SITE_FUNCTION.SITE_FUNCTION_id="siteService.siteFunctionList".id ### Cause: org.h2.jdbc.JdbcSQLException: Column "SITE_FUNCTION.SITE_FUNCTION_ID" not found; SQL statement: select "siteService".id as "id","siteService".NAME as "name","siteService.siteFunctionList".id as "siteFunctionList.id","siteService.siteFunctionList".NAME as "siteFunctionList.name","siteService.siteFunctionList".SITE_SERVICE_ID as "siteFunctionList.siteService.id" from SITE_SERVICE "siteService" left outer join SITE_FUNCTION on SITE_FUNCTION.SITE_SERVICE_id="siteService".id left outer join SITE_FUNCTION "siteService.siteFunctionList" on SITE_FUNCTION.SITE_FUNCTION_id="siteService.siteFunctionList".id [42122-193] ; bad SQL grammar []; nested exception is org.h2.jdbc.JdbcSQLException: Column "SITE_FUNCTION.SITE_FUNCTION_ID" not found; SQL statement: select "siteService".id as "id","siteService".NAME as "name","siteService.siteFunctionList".id as "siteFunctionList.id","siteService.siteFunctionList".NAME as "siteFunctionList.name","siteService.siteFunctionList".SITE_SERVICE_ID as "siteFunctionList.siteService.id" from SITE_SERVICE "siteService" left outer join SITE_FUNCTION on SITE_FUNCTION.SITE_SERVICE_id="siteService".id left outer join SITE_FUNCTION "siteService.siteFunctionList" on SITE_FUNCTION.SITE_FUNCTION_id="siteService.siteFunctionList".id [42122-193]

**Comment by easybest** [comment]
You have a problem with the usage, and you can see this pr: https://github.com/kopax/spring-data-mybatis-testing/pull/2

this pr include @OneToMany , rest projection and extend-xml issues.
